config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Dcp Tech Book App!'
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to "dcp tech book", '#', class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="Navber">
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Account<b class="caret">
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", current_user, class: 'dropdown-item' %>
            <a class="dropdown-item" href="#">Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
        <% else %>
        <li class="nav-item"><%= link_to "Log in", login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DcTechBook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_pack_tag 'application' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>書籍管理</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application' %>
</head>

<body class="bg-dark">
    <div class="login-box-wrap">
        <div class="container">
            <h1 style="text-shadow: 0px 0px 20px black;">書籍管理</h1>
            <%= form_for(@user, url: signup_path) do |f| %>
            <%= render 'shared/error_messages' %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation, 'Confirmation' %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <%= f.submit "登録", class: "btn btn-block btn-primary" %>
            <% end %>
        </div>
    </div>
</body>

</html>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>